/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ingested feeds with license attribution */
        get: operations["listFeeds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List operator branding marks and logo/data licenses */
        get: operations["listOperators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/route-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nationwide precomputed display route map
         * @description Returns simplified display-only route geometry generated from route-shapes artifacts. This geometry is not used for journey search.
         */
        get: operations["getRouteMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Station autocomplete (parent-station, multilingual prefix) */
        get: operations["suggestLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Place autocomplete: stations, stops, facilities, addresses */
        get: operations["suggestPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nearby places for a picked map point */
        get: operations["reversePlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Station detail: platforms and serving routes */
        get: operations["getStation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{id}/departures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Departure board for a station
         * @description Lists upcoming departures for feeds whose terms allow this presentation. ODPT-published timetable data is used for journey planning, but the API does not expose ODPT's published station/train timetable information as a departure-board dataset.
         */
        get: operations["getStationDepartures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Journey search (出発 / 到着 / 始発 / 終電)
         * @description Endpoints accept a station id (feedId:stopId) or geo:<lat>,<lon>. Times are seconds from the service-date midnight in the result timezone and may exceed 86400 or be negative.
         */
        get: operations["planJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guidance/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Guidance plan: ranked options, comparison basis, map geometry
         * @description A guide-UI contract over the planner: ranked options with metrics, cognitive load, decision factors, next action, coverage evidence and map geometry as first-class fields.
         */
        get: operations["planGuidance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/map/3d-scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bounded 3D building scene layer URLs for a viewport */
        get: operations["getMap3dScene"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ApiError: {
            error: string | {
                code?: string;
                message?: string;
                detail?: unknown;
            };
        };
        FeedListResponse: {
            feeds: {
                feedId: string;
                name: string;
                license: string;
                attribution?: string;
                country: string;
                version: string;
                fetchedAt: string;
                /** @description Stop extent; used to pick feeds for geographic queries. */
                bbox?: {
                    minLat: number;
                    minLon: number;
                    maxLat: number;
                    maxLon: number;
                };
                /** @description Earliest service date the feed's timetable describes (YYYYMMDD). */
                serviceStart?: string;
                /** @description Latest service date the feed's timetable describes (YYYYMMDD); the data's 'as of' date. */
                serviceEnd?: string;
                /** @description True when serviceEnd is before the request date: the timetable is a past snapshot kept usable via a forward roll. */
                stale?: boolean;
            }[];
        };
        SuggestResponse: {
            stations: {
                id: string;
                name: string;
                nameKana?: string;
                feedId: string;
                feedName: string;
                score: number;
                weight: number;
                /** @description Station coordinates, carried so map/guidance callers skip feed loads. */
                lat?: number;
                lon?: number;
                /**
                 * @description Rail-like station vs roadside stop, by serving mode.
                 * @enum {string}
                 */
                kind?: "station" | "stop";
            }[];
        };
        PlaceSuggestResponse: {
            places: {
                id: string;
                /** @description Endpoint accepted by the route planner: feed-qualified station id or geo:lat,lon. */
                endpoint: string;
                name: string;
                /** @enum {string} */
                kind: "station" | "stop" | "place" | "address";
                /** @enum {string} */
                source: "transit" | "osm" | "geocoder";
                lat: number;
                lon: number;
                score: number;
                weight: number;
                nameKana?: string;
                nameEn?: string;
                description?: string;
                feedId?: string;
                feedName?: string;
            }[];
            coverage: {
                sources: ("transit" | "osm" | "geocoder")[];
                kinds: ("station" | "stop" | "place" | "address")[];
                notices: {
                    /** @enum {string} */
                    severity: "info" | "warning";
                    message: string;
                }[];
            };
        };
        PlaceReverseResponse: {
            places: {
                id: string;
                /** @description Endpoint accepted by the route planner: feed-qualified station id or geo:lat,lon. */
                endpoint: string;
                name: string;
                /** @enum {string} */
                kind: "station" | "stop" | "place" | "address";
                /** @enum {string} */
                source: "transit" | "osm" | "geocoder";
                lat: number;
                lon: number;
                score: number;
                weight: number;
                nameKana?: string;
                nameEn?: string;
                description?: string;
                feedId?: string;
                feedName?: string;
                distanceMeters: number;
            }[];
            coverage: {
                sources: ("transit" | "osm" | "geocoder")[];
                kinds: ("station" | "stop" | "place" | "address")[];
                notices: {
                    /** @enum {string} */
                    severity: "info" | "warning";
                    message: string;
                }[];
            };
        };
        StationDetail: {
            id: string;
            name: string;
            nameKana?: string;
            lat: number;
            lon: number;
            feedId: string;
            platforms: {
                id: string;
                name: string;
                platformCode?: string;
                lat: number;
                lon: number;
            }[];
            routes: {
                name: string;
                mode: string;
                color?: string;
            }[];
        };
        DeparturesResponse: {
            stationId: string;
            date: string;
            timezone: string;
            departures: {
                /** @description The line (e.g. 山陽本線); a route models the line, not the train class. */
                routeName: string;
                /** @description Train class/種別 (普通 / 快速 / 特急 …) when the line carries mixed classes. */
                trainType?: string;
                mode: string;
                color?: string;
                headsign?: string;
                tripId: string;
                stopId: string;
                departureSecs: number;
                headwayBased: boolean;
                headwaySecs?: number;
            }[];
        };
        PlanResponse: {
            date: string;
            /** @enum {string} */
            type: "departure" | "arrival" | "first" | "last";
            timezone: string;
            from: {
                id: string;
                name: string;
            };
            to: {
                id: string;
                name: string;
            };
            journeys: {
                departureSecs: number;
                arrivalSecs: number;
                durationSecs: number;
                transferCount: number;
                fare?: {
                    currency: string;
                    /** @description きっぷ運賃. */
                    ticket: number;
                    /** @description ICカード運賃, when the source distinguishes it. */
                    ic?: number;
                };
                /** @description Walk from the geographic origin to the first stop (geo queries only). */
                accessWalkSecs?: number;
                /** @description Walk from the last stop to the geographic destination (geo queries only). */
                egressWalkSecs?: number;
                legs: ({
                    /** @enum {string} */
                    kind: "transit";
                    /** @description The line this leg runs on (e.g. 山陽本線); a route models the line, not the train class. */
                    routeName: string;
                    /** @description Train class/種別 (普通 / 快速 / 特急 …) when the line carries mixed classes. */
                    trainType?: string;
                    mode: string;
                    color?: string;
                    headsign?: string;
                    tripId: string;
                    from: {
                        id: string;
                        name: string;
                        platformCode?: string;
                    };
                    to: {
                        id: string;
                        name: string;
                        platformCode?: string;
                    };
                    departureSecs: number;
                    arrivalSecs: number;
                    /** @description True when times are worst-case bounds from headway operation. */
                    headwayBased: boolean;
                } | {
                    /** @enum {string} */
                    kind: "walk";
                    from: {
                        id: string;
                        name: string;
                        platformCode?: string;
                    };
                    to: {
                        id: string;
                        name: string;
                        platformCode?: string;
                    };
                    departureSecs: number;
                    arrivalSecs: number;
                })[];
            }[];
        };
        GuidancePlanResponse: {
            date: string;
            /** @enum {string} */
            type: "departure" | "arrival" | "first" | "last";
            timezone: string;
            from: {
                id: string;
                name: string;
            };
            to: {
                id: string;
                name: string;
            };
            live: {
                /** @enum {string} */
                mode: "manual" | "liveQuery";
                /** @enum {string} */
                tracking: "none" | "origin" | "destination" | "both";
                refreshAfterSecs: number;
                anchorSecs: number;
            };
            osm: {
                /** @enum {string} */
                status: "notApplicable" | "network" | "estimated";
                regionId?: string;
                attribution?: string;
            };
            coverage: {
                feeds: {
                    feedId: string;
                    name: string;
                    /** @description Transit modes actually used from this feed in returned options, when known. */
                    transitModes?: ("tram" | "subway" | "rail" | "bus" | "ferry" | "cableTram" | "aerialLift" | "funicular" | "trolleybus" | "monorail" | "air")[];
                    /** @description Latest service date this feed's timetable describes (YYYYMMDD); present when known. */
                    serviceEnd?: string;
                    /** @description True when this feed's data ended before the query date and was rolled forward to stay usable. */
                    stale?: boolean;
                }[];
                transitModes: ("tram" | "subway" | "rail" | "bus" | "ferry" | "cableTram" | "aerialLift" | "funicular" | "trolleybus" | "monorail" | "air")[];
                notices: {
                    /** @enum {string} */
                    severity: "info" | "warning";
                    /** @enum {string} */
                    code: "loadedDataScope" | "stationRailCandidateMissing" | "noRouteInLoadedData" | "constraintsApplied" | "constraintsNoRoute" | "staleFeedData";
                    message: string;
                    action?: string;
                    modes?: ("tram" | "subway" | "rail" | "bus" | "ferry" | "cableTram" | "aerialLift" | "funicular" | "trolleybus" | "monorail" | "air")[];
                    walk?: boolean;
                }[];
            };
            decision: {
                /** @enum {string} */
                strategy: "balanced" | "fastest" | "fewestTransfers" | "lowestFare" | "shortestWalk";
                recommendedOptionId?: string;
                primaryFactors: {
                    /** @enum {string} */
                    kind: "arrivalTime" | "duration" | "transferBurden" | "fare" | "walkingBurden" | "waitingBurden" | "reliability" | "directness";
                    /** @enum {string} */
                    effect: "advantage" | "tradeoff" | "risk";
                    /** @enum {string} */
                    magnitude: "small" | "medium" | "large";
                    deltaSecs?: number;
                    deltaCount?: number;
                    deltaAmount?: number;
                }[];
                tradeoffs: {
                    /** @enum {string} */
                    kind: "arrivalTime" | "duration" | "transferBurden" | "fare" | "walkingBurden" | "waitingBurden" | "reliability" | "directness";
                    /** @enum {string} */
                    effect: "advantage" | "tradeoff" | "risk";
                    /** @enum {string} */
                    magnitude: "small" | "medium" | "large";
                    deltaSecs?: number;
                    deltaCount?: number;
                    deltaAmount?: number;
                }[];
            };
            options: {
                id: string;
                rank: number;
                score: number;
                recommended: boolean;
                /** @enum {string} */
                selectedFor: "balanced" | "fastest" | "fewestTransfers" | "lowestFare" | "shortestWalk";
                /** @enum {string} */
                confidence: "high" | "medium" | "low";
                metrics: {
                    durationSecs: number;
                    transitSecs: number;
                    walkSecs: number;
                    waitSecs: number;
                    transferCount: number;
                    headwayLegCount: number;
                    fare?: {
                        currency: string;
                        /** @description きっぷ運賃. */
                        ticket: number;
                        /** @description ICカード運賃, when the source distinguishes it. */
                        ic?: number;
                    };
                };
                load: {
                    /** @enum {string} */
                    overall: "low" | "medium" | "high";
                    /** @enum {string} */
                    walking: "low" | "medium" | "high";
                    /** @enum {string} */
                    waiting: "low" | "medium" | "high";
                    /** @enum {string} */
                    transfer: "low" | "medium" | "high";
                    /** @enum {string} */
                    uncertainty: "low" | "medium" | "high";
                };
                decisionFactors: {
                    /** @enum {string} */
                    kind: "arrivalTime" | "duration" | "transferBurden" | "fare" | "walkingBurden" | "waitingBurden" | "reliability" | "directness";
                    /** @enum {string} */
                    effect: "advantage" | "tradeoff" | "risk";
                    /** @enum {string} */
                    magnitude: "small" | "medium" | "large";
                    deltaSecs?: number;
                    deltaCount?: number;
                    deltaAmount?: number;
                }[];
                nextAction?: {
                    /** @enum {string} */
                    kind: "walk" | "wait" | "board";
                    from: {
                        id: string;
                        name: string;
                        platformCode?: string;
                    };
                    to?: {
                        id: string;
                        name: string;
                        platformCode?: string;
                    };
                    departureSecs: number;
                    timeBudgetSecs: number;
                    routeName?: string;
                };
                map?: {
                    bounds: {
                        minLat: number;
                        minLon: number;
                        maxLat: number;
                        maxLon: number;
                    };
                    points: {
                        id: string;
                        name: string;
                        lat: number;
                        lon: number;
                        /** @enum {string} */
                        role: "origin" | "destination" | "stop" | "transfer";
                    }[];
                    segments: {
                        /** @enum {string} */
                        kind: "walk" | "transit";
                        fromPointId: string;
                        toPointId: string;
                        routeName?: string;
                        color?: string;
                        /** @enum {string} */
                        geometrySource: "osmWalk" | "estimatedWalk" | "gtfsShape" | "gsiRailCenterline" | "openRailwayMap" | "stopOrder" | "direct";
                        /** @enum {string} */
                        fallbackReason?: "noWalkingGraph" | "networkUnreachable";
                        polyline: {
                            lat: number;
                            lon: number;
                        }[];
                    }[];
                };
                journey: {
                    departureSecs: number;
                    arrivalSecs: number;
                    durationSecs: number;
                    transferCount: number;
                    fare?: {
                        currency: string;
                        /** @description きっぷ運賃. */
                        ticket: number;
                        /** @description ICカード運賃, when the source distinguishes it. */
                        ic?: number;
                    };
                    /** @description Walk from the geographic origin to the first stop (geo queries only). */
                    accessWalkSecs?: number;
                    /** @description Walk from the last stop to the geographic destination (geo queries only). */
                    egressWalkSecs?: number;
                    legs: ({
                        /** @enum {string} */
                        kind: "transit";
                        /** @description The line this leg runs on (e.g. 山陽本線); a route models the line, not the train class. */
                        routeName: string;
                        /** @description Train class/種別 (普通 / 快速 / 特急 …) when the line carries mixed classes. */
                        trainType?: string;
                        mode: string;
                        color?: string;
                        headsign?: string;
                        tripId: string;
                        from: {
                            id: string;
                            name: string;
                            platformCode?: string;
                        };
                        to: {
                            id: string;
                            name: string;
                            platformCode?: string;
                        };
                        departureSecs: number;
                        arrivalSecs: number;
                        /** @description True when times are worst-case bounds from headway operation. */
                        headwayBased: boolean;
                    } | {
                        /** @enum {string} */
                        kind: "walk";
                        from: {
                            id: string;
                            name: string;
                            platformCode?: string;
                        };
                        to: {
                            id: string;
                            name: string;
                            platformCode?: string;
                        };
                        departureSecs: number;
                        arrivalSecs: number;
                    })[];
                };
            }[];
        };
        OperatorBrandingResponse: {
            /** @description ISO timestamp the registry was generated. */
            generatedAt: string;
            operators: {
                /** @description Stable operator id, e.g. "odpt.Operator:Keikyu" or "feed:hanshin-rail". */
                id: string;
                /** @description Official name, e.g. "京浜急行電鉄". */
                name: string;
                /** @description Display short name, e.g. "京急". */
                nameShort: string;
                /** @description Short monogram shown when no licensed logo asset exists, e.g. "KK". */
                mark: string;
                /** @description Corporate brand color (hex, "#rrggbb"); absent when no single authoritative color is known. */
                brandColor?: string;
                /** @description Feeds whose legs belong to this operator (the feedId prefix of their ids). */
                feedIds: string[];
                /** @description Data license shared by this operator's feeds (e.g. "CC BY 4.0"). */
                dataLicense: string;
                /** @description Required data attribution, when the source mandates one. */
                dataAttribution?: string;
                /** @description Usage-terms / permission page (e.g. an ODPT operator data page). */
                termsUrl?: string;
                /** @description Present only when a license-cleared logo asset has been acquired. */
                logo?: {
                    /** @description Asset path served under the operator-logo base (operators/logos/...). */
                    asset: string;
                    /** @enum {string} */
                    format: "svg" | "png";
                    /** @description License of the logo asset itself (e.g. "Public domain", "CC BY-SA 4.0"). */
                    license: string;
                    /** @description Required credit line for the asset. */
                    attribution: string;
                    /** @description Human-readable source (e.g. "Wikimedia Commons", "事業者提供"). */
                    source: string;
                    sourceUrl?: string;
                };
            }[];
        };
        Map3dSceneResponse: {
            layers: ({
                id: string;
                /** @enum {string} */
                role: "building";
                /** @enum {string} */
                provider: "plateau";
                /** @enum {string} */
                format: "3dtiles";
                url: string;
                areaCode: string;
                areaName: string;
                /** @enum {string} */
                featureType: "bldg";
                /** @enum {string} */
                lod: "maxlod1" | "maxlod2";
                /** @enum {string} */
                textureMode: "auto" | "notexture" | "texture";
                attribution: string;
            } | {
                id: string;
                /** @enum {string} */
                role: "surface";
                /** @enum {string} */
                provider: "gsi";
                /** @enum {string} */
                format: "raster";
                tiles: string[];
                tileSize: number;
                minZoom: number;
                maxZoom: number;
                attribution: string;
            })[];
            notices: {
                /** @enum {string} */
                severity: "info" | "warning";
                /** @enum {string} */
                code: "unsupportedArea" | "layerLimit" | "zoomRequired";
                message: string;
            }[];
        };
        RouteMapResponse: {
            /** @enum {number} */
            version: 1;
            generatedAt: string;
            source: string;
            attribution: string;
            bbox?: {
                minLat: number;
                minLon: number;
                maxLat: number;
                maxLon: number;
            };
            feeds: {
                feedId: string;
                name: string;
                lineCount: number;
            }[];
            lines: {
                id: string;
                feedId: string;
                feedName: string;
                sourceRouteId: string;
                routeName: string;
                /** @enum {string} */
                mode: "tram" | "subway" | "rail" | "bus" | "ferry" | "cableTram" | "aerialLift" | "funicular" | "trolleybus" | "monorail" | "air";
                /** @enum {string} */
                provider: "gsiRailCenterline" | "openRailwayMap";
                color?: string;
                /** @enum {string} */
                colorSource?: "routeColor" | "feedStable";
                recorded?: boolean;
                patternCount?: number;
                coverage?: {
                    /** @enum {string} */
                    kind: "stopPairs";
                    expected: number;
                    covered: number;
                    ratio: number;
                };
                bbox: {
                    minLat: number;
                    minLon: number;
                    maxLat: number;
                    maxLon: number;
                };
                polyline: {
                    lat: number;
                    lon: number;
                }[];
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listFeeds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedListResponse"];
                };
            };
        };
    };
    listOperators: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorBrandingResponse"];
                };
            };
        };
    };
    getRouteMap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteMapResponse"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    suggestLocations: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResponse"];
                };
            };
            /** @description Invalid query parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    suggestPlaces: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceSuggestResponse"];
                };
            };
            /** @description Invalid query parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reversePlaces: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                limit?: number;
                radiusMeters?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceReverseResponse"];
                };
            };
            /** @description Invalid query parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getStation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feed-qualified station id (feedId:stopId). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationDetail"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getStationDepartures: {
        parameters: {
            query?: {
                date?: string;
                time?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Feed-qualified station id (feedId:stopId). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeparturesResponse"];
                };
            };
            /** @description Error. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    planJourney: {
        parameters: {
            query: {
                /** @description Origin: a station id (feedId:stopId) or geo:<lat>,<lon>. */
                from: string;
                /** @description Destination: a station id (feedId:stopId) or geo:<lat>,<lon>. */
                to: string;
                /** @description Optional display name for the origin. */
                fromLabel?: string;
                /** @description Optional display name for the destination. */
                toLabel?: string;
                /** @description Optional display label for each via, positionally matched to via[]. */
                viaLabel?: string[];
                /** @description Service date YYYYMMDD; defaults to today in the result timezone. */
                date?: string;
                /** @description HH:MM or HH:MM:SS; defaults to the current time. */
                time?: string;
                /** @description 出発 / 到着 / 始発 / 終電. */
                type?: "departure" | "arrival" | "first" | "last";
                /** @description Comma-separated transit modes to allow (pre-scan filter), e.g. rail,bus. */
                allowModes?: string;
                /** @description Comma-separated transit modes to avoid (pre-scan filter), e.g. bus,air,ferry. */
                avoidModes?: string;
                /** @description When true, exclude any itinerary containing a walking segment. */
                avoidWalk?: "true" | "false";
                maxTransfers?: number;
                numItineraries?: number;
                /** @description Up to 3 経由 waypoints, repeated: a station id or geo:<lat>,<lon>. Departure/arrival searches only. */
                via?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Invalid query parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable: endpoints identical, via unsupported, or search window too dense. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    planGuidance: {
        parameters: {
            query: {
                /** @description Origin: a station id (feedId:stopId) or geo:<lat>,<lon>. */
                from: string;
                /** @description Destination: a station id (feedId:stopId) or geo:<lat>,<lon>. */
                to: string;
                /** @description Optional display name for the origin. */
                fromLabel?: string;
                /** @description Optional display name for the destination. */
                toLabel?: string;
                /** @description Optional display label for each via, positionally matched to via[]. */
                viaLabel?: string[];
                /** @description Service date YYYYMMDD; defaults to today in the result timezone. */
                date?: string;
                /** @description HH:MM or HH:MM:SS; defaults to the current time. */
                time?: string;
                /** @description 出発 / 到着 / 始発 / 終電. */
                type?: "departure" | "arrival" | "first" | "last";
                /** @description Comma-separated transit modes to allow (pre-scan filter), e.g. rail,bus. */
                allowModes?: string;
                /** @description Comma-separated transit modes to avoid (pre-scan filter), e.g. bus,air,ferry. */
                avoidModes?: string;
                /** @description When true, exclude any itinerary containing a walking segment. */
                avoidWalk?: "true" | "false";
                maxTransfers?: number;
                numItineraries?: number;
                strategy?: "balanced" | "fastest" | "fewestTransfers" | "lowestFare" | "shortestWalk";
                live?: "true" | "false";
                tracking?: "none" | "origin" | "destination" | "both";
                /** @description Up to 3 経由 waypoints, repeated: a station id or geo:<lat>,<lon>. Departure/arrival searches only. */
                via?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidancePlanResponse"];
                };
            };
            /** @description Invalid query parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable: endpoints identical, via unsupported, or search window too dense. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMap3dScene: {
        parameters: {
            query: {
                minLat: number;
                minLon: number;
                maxLat: number;
                maxLon: number;
                maxLod: number;
                textureMode: "auto" | "notexture" | "texture";
                purpose: "routeContext" | "viewport";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Map3dSceneResponse"];
                };
            };
            /** @description Invalid query parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
